# Generated by Django 5.0.2 on 2024-02-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="carnet",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
